# Generated by Django 3.0.6 on 2020-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_count_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='url', max_length=2083),
            preserve_default=False,
        ),
    ]
