# Generated by Django 3.0.6 on 2020-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='prod_price',
            field=models.FloatField(),
        ),
    ]
