# Generated by Django 3.0.6 on 2020-06-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200602_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
    ]
