# Generated by Django 3.0.6 on 2020-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200603_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='admin_comment',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='is_ordered',
            field=models.CharField(default='approved', max_length=20),
            preserve_default=False,
        ),
    ]
